### ISSUE TITLE
NoSuchMedhod fromNanos

### ISSUE THREAD

**Issue by octavz** [zio/interop-cats#155]
val zio = "1.0.0-RC18-1+27-ac79039b-SNAPSHOT"
  val zioInteropCats = "2.0.0.0-RC11+1-87261427-SNAPSHOT"
```
An unchecked error was produced.
root ║ java.lang.NoSuchMethodError: 'zio.duration.Duration$Finite zio.duration.Duration$.fromNanos(long)'
root ║ 	at zio.interop.CatsEffectInstances$$anon$4.$anonfun$sleep$2(cats.scala:88)
root ║ 	at zio.clock.package$.$anonfun$sleep$3(package.scala:86)
root ║ 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:517)
root ║ 	at zio.internal.FiberContext.$anonfun$fork$2(FiberContext.scala:681)
root ║ 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
root ║ 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
root ║ 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I can provide full stack but this seemed relevant. Thank you.

**Comment by ghostdogpr** [comment]
That’s because you use a ZIO snapshot. We don’t build interop-cats based on snapshots, only releases. That won’t be a problem once 1.0 is out btw.
