### ISSUE TITLE
java.lang.NoSuchMethodError: cats.effect.ContextShift.$init$(Lcats/effect/ContextShift;)

### ISSUE THREAD

**Issue by don41382** [zio/interop-cats#35]
I am using the latest ZIO and ZIOInteropCats Version and get a `MethodNotFoundException` when using the Transactor vom Doobie.

*build.sbt*
```
scalaVersion := "2.12.8"

val ZIOVersion = "1.0.0-RC11-1"
val ZIOInteropCats = "2.0.0.0-RC2"

libraryDependencies ++= Seq(
  // ZIO
  "dev.zio" %% "zio"  % ZIOVersion,
  "dev.zio" %% "zio-streams" % ZIOVersion,
  "dev.zio" %% "zio-interop-cats" % ZIOInteropCats,
  "org.tpolecat" %% "doobie-core"      % "0.7.0",
  "org.tpolecat" %% "doobie-postgres"  % "0.7.0",
...
```

*DoobieTweetRepo.scala*
```
import doobie.implicits._
import doobie.util.transactor.Transactor
import zio._
import zio.interop.catz._
...
object DoobieTweetRepo {

  // this is line 40
  def xa(db: DBConfig): Transactor[Task]  = Transactor.fromDriverManager[Task](
    "org.postgresql.Driver", db.url, db.username, db.password
  )

}
```

*Error*
```
java.lang.NoSuchMethodError: cats.effect.ContextShift.$init$(Lcats/effect/ContextShift;)V
zio-twitter-test[ERROR] 	at zio.interop.CatsInstances$$anon$3.<init>(catsjvm.scala:54)
zio-twitter-test[ERROR] 	at zio.interop.CatsInstances.zioContextShift(catsjvm.scala:54)
zio-twitter-test[ERROR] 	at com.rocketsolutions.db.DoobieTweetRepo$.xa(DoobieTweetRepo.scala:40)
zio-twitter-test[ERROR] 	at com.rocketsolutions.TwitterDemo$$anon$1.transactor(TwitterDemo.scala:53)
zio-twitter-test[ERROR] 	at com.rocketsolutions.db.DoobieTweetRepo$$anon$1.initTable(DoobieTweetRepo.scala:24)
zio-twitter-test[ERROR] 	at com.rocketsolutions.TwitterDemo$.$anonfun$main$1(TwitterDemo.scala:42)
zio-twitter-test[ERROR] 	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:471)
zio-twitter-test[ERROR] 	at zio.internal.FiberContext.$anonfun$fork$1(FiberContext.scala:604)
zio-twitter-test[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
zio-twitter-test[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
zio-twitter-test[ERROR] 	at java.lang.Thread.run(Thread.java:748)
```

Any idea?

**Comment by don41382** [comment]
Updated doobie to Version `0.8.0-RC1` fixed the issue.

```
  "org.tpolecat" %% "doobie-core"      % "0.8.0-RC1",
  "org.tpolecat" %% "doobie-postgres"  % "0.8.0-RC1",
```
